name: Build and commit India funding context

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 1" # Mondays 04:00 UTC (optional)

permissions:
  contents: write

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    env:
      KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
      KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install kaggle

      - name: Configure Kaggle and sanity check
        run: |
          mkdir -p ~/.kaggle
          echo "{\"username\":\"${KAGGLE_USERNAME}\",\"key\":\"${KAGGLE_KEY}\"}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json
          kaggle -v || true
          kaggle datasets list -s "startup-funding-india" -p 1 || true

      - name: Ensure Python can import repo packages
        run: |
          echo "PYTHONPATH=${PYTHONPATH}:${GITHUB_WORKSPACE}" >> "$GITHUB_ENV"
          python - << 'PY'
          import sys, os
          print("sys.path:", sys.path)
          print("workspace contents:", os.listdir("."))
          assert os.path.exists("models/training/build_india_funding_context.py"), "build_india_funding_context.py not found at models/training/"
          PY

      - name: Build India funding index JSON
        run: |
          # Call by file path to avoid package resolution issues
          python models/training/build_india_funding_context.py --dataset-ref sandeepnandi48/startup-funding-india-cleaned
          test -f data/india_funding_index.json
          ls -lh data/india_funding_index.json

      - name: Commit and push data/india_funding_index.json
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(data): update India funding index from Kaggle"
          file_pattern: data/india_funding_index.json
