name: Build and commit India funding context

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 1" # Mondays 04:00 UTC (optional)

permissions:
  contents: write

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    env:
      KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
      KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install kaggle

      - name: Configure Kaggle and sanity check
        run: |
          mkdir -p ~/.kaggle
          echo "{\"username\":\"${KAGGLE_USERNAME}\",\"key\":\"${KAGGLE_KEY}\"}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json
          kaggle -v || true
          kaggle datasets list -s "startup-funding-india" -p 1 || true

      - name: Try to build India funding index JSON (non-fatal)
        id: build_ctx
        continue-on-error: true
        run: |
          # Your repo has the script at training/build_india_funding_context.py
          python training/build_india_funding_context.py --dataset-ref sandeepnandi48/startup-funding-india-cleaned
          if [ -f data/india_funding_index.json ]; then
            echo "ok=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Fallback: write placeholder India funding index JSON
        if: steps.build_ctx.outcome != 'success'
        run: |
          mkdir -p data
          cat > data/india_funding_index.json << 'JSON'
          {
            "sectors": {
              "FinTech": {
                "rounds_total": 0,
                "median_amount_inr": null,
                "yearly_rounds": [],
                "round_mix": [],
                "top_investors": []
              },
              "E-commerce & D2C": {
                "rounds_total": 0,
                "median_amount_inr": null,
                "yearly_rounds": [],
                "round_mix": [],
                "top_investors": []
              },
              "Digital Health": {
                "rounds_total": 0,
                "median_amount_inr": null,
                "yearly_rounds": [],
                "round_mix": [],
                "top_investors": []
              },
              "Clean Energy": {
                "rounds_total": 0,
                "median_amount_inr": null,
                "yearly_rounds": [],
                "round_mix": [],
                "top_investors": []
              }
            }
          }
          JSON
          ls -lh data/india_funding_index.json

      - name: Commit and push data/india_funding_index.json
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(data): update India funding index (Kaggle or placeholder)"
          file_pattern: data/india_funding_index.json
